const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');

function loadContent(){const context={window:{},Map,Set,Array,Object,Number,String,Math,RegExp};vm.createContext(context);vm.runInContext(read('public/question-pack-02.js'),context);vm.runInContext(read('public/question-pack-03.js'),context);vm.runInContext(read('public/question-pack-lesson.js'),context);vm.runInContext(read('public/content-catalog.js'),context);return context.window.ManjingoContent;}

test('learning path links unlocked stages into lesson route',()=>{const source=read('public/learning-path-ui.js');assert.match(source,/\.\/lesson\.html\?kpId=/);assert.match(source,/encodeURIComponent\(lesson\.kpId\)/);assert.match(source,/nextLesson\(stage\)/);});
test('lesson page loads browser flow dependencies in safe order',()=>{const html=read('public/lesson.html');const scripts=['./catalog-runtime.js','./local-learning.js','./lesson-content-reading.js','./lesson-content.js','./local-lesson.js'];let last=-1;for(const src of scripts){const index=html.indexOf(`src="${src}"`);assert.ok(index>last,`${src} missing or loaded out of order`);last=index;}assert.match(read('public/content-catalog.js'),/practice-effectiveness\.js/);assert.match(html,/new URLSearchParams\(location\.search\)\.get\('kpId'\)/);assert.match(html,/ManjingoLocalLesson\.open\(kpId,app\)/);});
test('local lesson practice submits exact KP answers while targeted progress is measured at skill level',()=>{const source=read('public/local-lesson.js');assert.match(source,/filter\(q=>q\.kpId===kpId\)/);assert.match(source,/submit\(q\.kpId,correct,\{questionId:q\.id,selectedAnswer:value,correctAnswer:displayAnswer\(q\),conceptKey:q\.misconceptionKey,conceptLabel:q\.misconceptionLabel\}\)/);assert.match(source,/skillMasteryRecord\(state\.skillId,state\.kp\.kpId,learning\)/);assert.match(source,/state\.questions\.length/);});
test('content catalog tags multiple core questions with shared misconception concepts',()=>{const content=loadContent();const yi=content.questions.filter(q=>q.kpId==='kp_p3_yi'&&q.misconceptionKey==='yi_reason_vs_tool');assert.ok(yi.length>=2);assert.ok(yi.every(q=>q.misconceptionLabel));assert.match(read('public/content-catalog.js'),/qi_pronoun_vs_modal/);assert.match(read('public/content-catalog.js'),/sentence_object_fronting/);});
test('daily question selector prefers a concept review question over generic KP questions',()=>{const content=loadContent(),conceptQuestions=content.questions.filter(q=>q.kpId==='kp_p3_yi'&&q.misconceptionKey==='yi_reason_vs_tool');assert.ok(conceptQuestions.length>=2);const target=conceptQuestions[1],plan={targetCount:1,items:[{kpId:'kp_p3_yi',category:'weak',priority:2,conceptReview:true,conceptKey:'yi_reason_vs_tool',conceptLabel:'「以」：原因義 vs 工具義',conceptMastery:30,conceptQuestionIds:[target.id]}]},selected=content.selectQuestionsForPlan(plan,content.questions,1);assert.equal(selected.length,1);assert.equal(selected[0].id,target.id);assert.equal(selected[0].conceptReview,true);assert.equal(selected[0].conceptKey,'yi_reason_vs_tool');assert.equal(selected[0].conceptMastery,30);});
test('targeted weakness practice skips lesson intro and prioritizes misconception questions',()=>{const lesson=read('public/local-lesson.js'),dashboard=read('public/mastery-dashboard.js');assert.match(lesson,/function targetedQuestions\(kpId,limit\)/);assert.match(lesson,/params\.get\('mode'\)==='practice'/);assert.match(lesson,/reteach\?conceptReteachQuestions\(kpId,focus,skillId\):remedial\?remedialQuestions\(kpId,focus,skillId\):targetedQuestions\(kpId,5,skillId\)/);assert.match(lesson,/if\(targeted\)\{renderQuestion\(app,state\);return\}/);assert.match(lesson,/weight\.get\(String\(b\.id\)\)/);assert.match(dashboard,/mode=practice/);assert.match(dashboard,/立即補強/);});
test('targeted remediation carries one skill identity across multiple KP routes',()=>{const lesson=read('public/local-lesson.js'),policy=read('public/practice-effectiveness.js');assert.match(lesson,/function skillQuestionPool\(skillId,kpId\)/);assert.match(lesson,/Array\.isArray\(q\.skillIds\).*includes\(id\)/);assert.match(lesson,/getSkillRemediationStatus\(skillId,skillIds\)/);assert.match(lesson,/dominantMisconception\(kpId,skillId\)/);assert.match(lesson,/skillId:state\.skillId\|\|null,routeKpId:state\.kp\.kpId,kpId:state\.kp\.kpId/);assert.match(policy,/function historyForSkill\(skillId,kpIds,learningOverride\)/);assert.match(policy,/tagged\)return tagged===id/);});
test('low-yield targeted practice routes through remedial teaching before two-question verification',()=>{const lesson=read('public/local-lesson.js'),policy=read('public/practice-effectiveness.js');assert.match(policy,/needsRemediation/);assert.match(policy,/lowYieldDelta:8/);assert.match(lesson,/function renderRemedial\(app,state\)/);assert.match(lesson,/自適應補救/);assert.match(lesson,/跨題錯誤概念/);assert.match(lesson,/做 2 題驗證/);assert.match(lesson,/if\(remedial\)\{if\(resumed\)renderQuestion\(app,state\);else renderRemedial\(app,state\);return\}/);assert.match(lesson,/補救驗證完成/);});
test('failed remedial verification escalates into concept reteach with three cross-context checks',()=>{const lesson=read('public/local-lesson.js'),policy=read('public/practice-effectiveness.js');assert.match(policy,/function interventionOutcome\(history,options\)/);assert.match(policy,/needsConceptReteach/);assert.match(lesson,/function conceptReteachQuestions\(kpId,focus\)/);assert.match(lesson,/function renderConceptReteach\(app,state\)/);assert.match(lesson,/概念重教/);assert.match(lesson,/三步判斷/);assert.match(lesson,/做 3 題跨語境驗證/);assert.match(lesson,/if\(reteach\)\{if\(resumed\)renderQuestion\(app,state\);else renderConceptReteach\(app,state\);return\}/);assert.match(lesson,/strategy:state\.reteach\?'reteach'/);});
test('remedial lesson targets dominant concept and verifies same-concept questions first',()=>{const lesson=read('public/local-lesson.js'),learning=read('public/local-learning.js');assert.match(learning,/function getMisconceptionConcepts\(kpId\)/);assert.match(lesson,/getMisconceptionConcepts/);assert.match(lesson,/conceptLabel/);assert.match(lesson,/conceptMatches/);assert.match(lesson,/q=>String\(q\.misconceptionKey\|\|''\)===String\(focus\.conceptKey\)/);assert.match(lesson,/這個概念錯誤累積/);assert.match(lesson,/function remedialQuestions\(kpId,focus\)/);});
test('remedial and reteach flows persist independent concept mastery before and after verification',()=>{const lesson=read('public/local-lesson.js'),learning=read('public/local-learning.js');assert.match(learning,/function getConceptMastery\(conceptKey\)/);assert.match(lesson,/startConceptMastery/);assert.match(lesson,/目前概念掌握度/);assert.match(lesson,/getConceptMastery\(state\.focus\.conceptKey\)/);assert.match(lesson,/conceptBeforeMastery:conceptBefore/);assert.match(lesson,/conceptAfterMastery:conceptAfter/);assert.match(lesson,/conceptDelta/);});
test('targeted practice compares mastery before and after and reports round accuracy',()=>{const source=read('public/local-lesson.js');assert.match(source,/startMastery:Number\(p\.mastery\|\|0\)/);assert.match(source,/state\.answeredCount\+=1/);assert.match(source,/if\(correct\)state\.correctCount\+=1/);assert.match(source,/掌握度：/);assert.match(source,/→/);assert.match(source,/本輪答對/);assert.match(source,/state\.correctCount/);});
test('targeted completion uses practice-specific labels, explicit deltas, and dashboard return',()=>{const source=read('public/local-lesson.js');assert.match(source,/state\.targeted\?'完成補強':'完成本課'/);assert.match(source,/function deltaLabel\(delta\)/);assert.match(source,/\?'↑'\+delta/);assert.match(source,/\?'↓'\+Math\.abs\(delta\):'持平'/);assert.match(source,/\.\/index\.html#masteryDashboard/);assert.match(source,/返回學習成果/);});
test('wrong answers prefer per-question feedback and fall back to KP lesson',()=>{const source=read('public/local-lesson.js');assert.match(source,/function teachingFeedback\(state,q,value\)/);assert.match(source,/q&&q\.explanation/);assert.match(source,/q&&q\.misconception/);assert.match(source,/q&&q\.example/);assert.match(source,/lesson\.explanation/);assert.match(source,/lesson\.tip/);assert.match(source,/lesson\.examples/);assert.match(source,/你可能混淆了：/);assert.match(source,/!correct&&normal\(b\.textContent\)===normal\(q\.a\)/);});
test('core particle pack carries question-level teaching metadata',()=>{const context={window:{}};vm.createContext(context);vm.runInContext(read('public/question-pack-03.js'),context);const qs=context.window.ManjingoQuestionPack03.questions;const rich=qs.filter(q=>q.explanation);assert.ok(rich.length>=20);const yi=qs.find(q=>q.q.includes('不以物喜'));assert.ok(yi.explanation);assert.ok(yi.misconception);assert.ok(yi.example);});
test('daily quiz surfaces misconception review and confirms repaired pattern',()=>{const html=read('public/index.html');assert.match(html,/misconceptionReview/);assert.match(html,/🔁 錯題重溫/);assert.match(html,/你已修正這個錯誤模式/);assert.match(html,/這題仍會保留較低的複習權重/);assert.match(html,/resolvedMisconceptions/);assert.match(html,/remainingMisconceptionWeight/);assert.match(html,/learning\(\)\?learning\(\)\.submit\(q\.kpId,correct/);assert.match(html,/selectedAnswer:value/);assert.match(html,/correctAnswer:displayAnswer\(q\)/);assert.match(html,/queueCloudAnswer\(q,answerId,value\)/);});
test('daily quiz surfaces concept review label and concept mastery feedback',()=>{const html=read('public/index.html');assert.match(html,/isConcept=!!q\.conceptReview/);assert.match(html,/🧩 概念重溫/);assert.match(html,/q\.conceptLabel/);assert.match(html,/q\.conceptMastery/);assert.match(html,/result\.conceptMastery/);assert.match(html,/category\.concept/);assert.match(html,/conceptKey:q\.misconceptionKey/);});
test('lesson completion returns learner to learning path',()=>{const source=read('public/local-lesson.js');assert.match(source,/returnHref=state\.targeted\?'\.\/index\.html#masteryDashboard':'\.\/index\.html'/);assert.match(source,/returnLabel=state\.targeted\?'返回學習成果':'回到學習路徑'/);});
