const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
function load(){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js','public/lesson-content-reading.js','public/lesson-content.js'])vm.runInContext(read(file),context);return context.window}
test('all 86 teachable knowledge points build a usable lesson',()=>{const w=load(),kps=w.ManjingoContent.knowledgePoints.filter(k=>k.teachable!==false);assert.equal(kps.length,86);for(const kp of kps){const lesson=w.ManjingoLessonContent.build(kp);assert.ok(lesson.title,`${kp.kpId} missing lesson title`);assert.ok(lesson.explanation,`${kp.kpId} missing explanation`);assert.ok(lesson.tip,`${kp.kpId} missing tip`);assert.ok(Array.isArray(lesson.examples),`${kp.kpId} examples must be an array`)}});
test('every teachable knowledge point has at least three practice questions',()=>{const w=load(),counts=new Map();for(const q of w.ManjingoContent.questions)counts.set(q.kpId,(counts.get(q.kpId)||0)+1);assert.deepEqual(Array.from(w.ManjingoContent.knowledgePoints.filter(k=>k.teachable!==false&&(counts.get(k.kpId)||0)<3).map(k=>[k.kpId,counts.get(k.kpId)||0])),[])});
test('new stage 1 function words build language lessons rather than set-text lessons',()=>{const w=load();for(const id of ['kp_virtual_wei','kp_virtual_zhe','kp_virtual_suo','kp_virtual_ye']){const kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId===id),lesson=w.ManjingoLessonContent.build(kp);assert.ok(kp);assert.match(kp.type,/虛詞/);assert.ok(lesson.explanation.length>0&&lesson.tip.length>0)}});
test('new stage 1 reading foundations build transferable language lessons',()=>{const w=load();for(const id of ['kp_read_sentence_core','kp_read_context_clues','kp_read_logical_relation','kp_syn_negative_patterns']){const kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId===id),lesson=w.ManjingoLessonContent.build(kp);assert.ok(kp);assert.ok(lesson.title&&lesson.explanation&&lesson.tip);assert.equal(kp.textId,'CROSS')}});
test('new stage 1 translation foundations build transferable language lessons',()=>{const w=load();for(const id of ['kp_syn_interrogative_patterns','kp_trans_function_word','kp_trans_supplement','kp_trans_ancient_modern']){const kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId===id),lesson=w.ManjingoLessonContent.build(kp);assert.ok(kp,`missing ${id}`);assert.ok(lesson.title&&lesson.explanation&&lesson.tip,`${id} needs lesson content`);assert.ok(Array.isArray(lesson.examples));assert.equal(kp.textId,'CROSS')}});
test('single-sentence transfer builds a usable transferable lesson',()=>{const w=load(),kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId==='kp_transfer_single_sentence'),lesson=w.ManjingoLessonContent.build(kp);assert.ok(kp);assert.equal(kp.textId,'CROSS');assert.match(kp.type,/篇章/);assert.ok(lesson.title&&lesson.explanation&&lesson.tip);});
test('stage 2 core-language KPs build transferable lessons',()=>{const w=load();for(const id of ['kp_virtual_hu','kp_virtual_qie','kp_virtual_yan','kp_lex_tongjia','kp_lex_intentional','kp_lex_semantic_role']){const kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId===id),lesson=w.ManjingoLessonContent.build(kp);assert.ok(kp,`missing ${id}`);assert.equal(kp.textId,'CROSS');assert.ok(lesson.title&&lesson.explanation&&lesson.tip,`${id} needs lesson content`);assert.ok(Array.isArray(lesson.examples));}});
test('second stage 2 sentence and reading KPs build transferable lessons',()=>{const w=load();for(const id of ['kp_syn_attributive_postpose','kp_syn_fixed_patterns','kp_read_parallel_inference']){const kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId===id),lesson=w.ManjingoLessonContent.build(kp);assert.ok(kp,`missing ${id}`);assert.equal(kp.textId,'CROSS');assert.ok(lesson.title&&lesson.explanation&&lesson.tip,`${id} needs lesson content`);assert.ok(Array.isArray(lesson.examples));}});
test('stage 2 closeout KPs build transferable lessons',()=>{const w=load();for(const id of ['kp_read_actor_tracking','kp_read_unknown_word_tolerance','kp_trans_fluency','kp_transfer_sentence_pair','kp_transfer_micro_passage']){const kp=w.ManjingoContent.knowledgePoints.find(x=>x.kpId===id),lesson=w.ManjingoLessonContent.build(kp);assert.ok(kp,`missing ${id}`);assert.equal(kp.textId,'CROSS');assert.ok(lesson.title&&lesson.explanation&&lesson.tip,`${id} needs lesson content`);assert.ok(Array.isArray(lesson.examples));}});
test('all dedicated reading lessons point to known knowledge points',()=>{const w=load(),ids=new Set(w.ManjingoContent.knowledgePoints.map(k=>k.kpId));assert.deepEqual(Array.from(Object.keys(w.ManjingoReadingLessons).filter(id=>!ids.has(id))),[])});
test('all 48 core pack03 questions have question-level explanations',()=>{const w=load(),pack=w.ManjingoQuestionPack03.questions;assert.equal(pack.length,48);assert.deepEqual(Array.from(pack.filter(q=>!q.explanation).map(q=>q.id)),[])});
test('all 96 reading pack02 questions have teaching explanations',()=>{const w=load(),pack=w.ManjingoQuestionPack02.questions;assert.equal(pack.length,96);assert.deepEqual(Array.from(pack.filter(q=>!q.explanation).map(q=>q.id)),[]);for(const q of pack)assert.match(q.explanation,new RegExp(q.a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),`${q.id} explanation should identify its answer`)});

test('lesson completion shares intervention-aware CTA logic with session summary',()=>{const source=read('public/local-lesson.js');assert.match(source,/function completionAction\(state\)/);assert.match(source,/summary&&typeof summary\.lessonAction==='function'/);assert.match(source,/recordTargetedSession\(state\);[\s\S]*action=completionAction\(state\)/);assert.match(source,/href="\$\{action\.href\}"/);assert.match(source,/\$\{action\.label\}/);});
