const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
function load(customKnowledge,history=[],options={}){const store=new Map(),context={window:{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},Map,Set,Array,Object,Number,String,Math,RegExp,Date,JSON,encodeURIComponent};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js','public/curriculum-v1.js','public/question-metadata-v1.js'])vm.runInContext(read(file),context);context.window.ManjingoLocalLearning={getKnowledge(kpId){if(customKnowledge&&Object.prototype.hasOwnProperty.call(customKnowledge,kpId))return customKnowledge[kpId];if(options.fallback===false)return{mastery:0,attempts:0,lastCorrect:null,lastAnsweredAt:null,misconceptions:{}};return{mastery:50,attempts:1,lastCorrect:true,lastAnsweredAt:'2026-09-10T12:00:00.000Z',misconceptions:{}}},getPracticeHistory(opts={}){return history.filter(item=>!opts.kpId||String(item.kpId)===String(opts.kpId))}};vm.runInContext(read('public/practice-effectiveness.js'),context);context.window.ManjingoPracticeEffectiveness=context.ManjingoPracticeEffectiveness;vm.runInContext(read('public/skill-evidence-v1.js'),context);vm.runInContext(read('public/skill-mastery-v1.js'),context);vm.runInContext(read('public/skill-results-v1.js'),context);vm.runInContext(read('public/mastery-dashboard.js'),context);return context.window.ManjingoMasteryDashboard;}
test('mastery dashboard covers 49 core skills in six curriculum domains',()=>{const d=load().build();assert.equal(d.total,49);assert.equal(d.groups.length,6);assert.deepEqual(Array.from(d.groups,g=>g.title),['詞彙與語義','文言虛詞','文言句法','閱讀策略','翻譯','陌生語境遷移'])});
test('mastery dashboard derives overall and weak counts from skill projections',()=>{const d=load().build();assert.equal(d.overall,50);assert.equal(d.mastered,0);assert.equal(d.weak,49);assert.equal(d.unattempted,0)});
test('untouched skills stay pending instead of being counted as weak',()=>{const dashboard=load({},[],{fallback:false}),d=dashboard.build();assert.equal(d.total,49);assert.equal(d.attempted,0);assert.equal(d.unattempted,49);assert.equal(d.weak,0);assert.equal(d.mastered,0);assert.equal(d.groups.reduce((n,g)=>n+g.unattempted,0),49);assert.equal(dashboard.weakest(d.groups.find(g=>g.id==='fw'),3).length,0)});
test('49 high legacy projections never create a false all-mastered green light',()=>{const catalog=load({},[],{fallback:false}),knowledge={};for(const item of catalog.build().items)for(const kpId of item.kpIds)knowledge[kpId]={mastery:100,attempts:20,lastCorrect:true,lastAnsweredAt:'2026-09-11T12:00:00Z',misconceptions:{}};const d=load(knowledge,[],{fallback:false}).build();assert.equal(d.attempted,49);assert.equal(d.mastered,0);assert.equal(d.provisional,49)});
test('attempted zero-mastery alias marks the shared skill weak once',()=>{const dashboard=load({kp_virtual_er:{mastery:0,attempts:1,lastCorrect:false,lastAnsweredAt:'2026-09-10T12:00:00.000Z',misconceptions:{}}},[],{fallback:false}),d=dashboard.build(),particles=d.groups.find(g=>g.id==='fw');assert.equal(d.attempted,1);assert.equal(d.unattempted,48);assert.equal(d.weak,1);assert.equal(particles.weak,1);assert.deepEqual(Array.from(dashboard.weakest(particles,3),x=>x.skillId),['fw.er'])});
test('function-word aliases appear as one particle skill each',()=>{const ids=new Set(load({},[],{fallback:false}).build().groups.find(g=>g.id==='fw').items.map(x=>x.skillId));for(const id of ['fw.zhi','fw.er','fw.yi','fw.wei','fw.zhe','fw.suo','fw.ye','fw.hu','fw.qie','fw.yan'])assert.ok(ids.has(id),`${id} missing from particle group`)});
test('stage 2 lexical skills appear in the lexical domain',()=>{const ids=new Set(load({},[],{fallback:false}).build().groups.find(g=>g.id==='lex').items.map(x=>x.skillId));for(const id of ['lex.tongjia','lex.intentional','lex.semantic-role'])assert.ok(ids.has(id),`${id} missing from lexical group`)});
test('reading foundations appear in reading strategy domain',()=>{const ids=new Set(load({},[],{fallback:false}).build().groups.find(g=>g.id==='read').items.map(x=>x.skillId));for(const id of ['read.sentence-core','read.context-clues','read.logical-relation'])assert.ok(ids.has(id))});
test('sentence foundations appear in syntax domain',()=>{const ids=new Set(load({},[],{fallback:false}).build().groups.find(g=>g.id==='syn').items.map(x=>x.skillId));for(const id of ['syn.negative-patterns','syn.interrogative-patterns','syn.judgment'])assert.ok(ids.has(id))});
test('translation foundations appear in translation domain',()=>{const ids=new Set(load({},[],{fallback:false}).build().groups.find(g=>g.id==='trans').items.map(x=>x.skillId));for(const id of ['trans.function-word','trans.supplement','trans.ancient-modern','trans.fluency'])assert.ok(ids.has(id))});
test('transfer skills have their own learner-facing domain',()=>{const ids=new Set(load({},[],{fallback:false}).build().groups.find(g=>g.id==='transfer').items.map(x=>x.skillId));for(const id of ['transfer.single-sentence','transfer.sentence-pair','transfer.micro-passage'])assert.ok(ids.has(id))});
test('stage 3 argumentation and long-passage previews do not count in core results',()=>{const all=new Set(load({},[],{fallback:false}).build().items.map(x=>x.skillId));for(const id of ['read.argumentation','transfer.short-passage','transfer.mixed'])assert.equal(all.has(id),false)});
test('early results hero foregrounds accumulated skill evidence before verified mastery',()=>{
 const dashboard=load({},[],{fallback:false});
 const hero=dashboard.heroModel({total:49,attempted:8,mastered:0,provisional:6,weak:2,unattempted:41});
 assert.equal(hero.mode,'evidence');
 assert.equal(hero.primaryValue,'8 / 49');
 assert.equal(hero.primaryLabel,'已建立證據');
 assert.equal(hero.headline,'已建立 8 / 49 項技能證據');
 assert.match(hero.detail,/✅ 已驗證 0/);
 assert.match(hero.detail,/🟡 待驗證 6/);
 assert.match(hero.detail,/🎯 弱項 2/);
});

test('results hero switches back to verified mastery once reliable mastery exists',()=>{
 const dashboard=load({},[],{fallback:false});
 const hero=dashboard.heroModel({total:49,attempted:12,mastered:3,provisional:7,weak:2,unattempted:37});
 assert.equal(hero.mode,'verified');
 assert.equal(hero.primaryValue,'3 / 49');
 assert.equal(hero.primaryLabel,'已驗證掌握');
 assert.equal(hero.headline,'你已開始 12 / 49 個核心技能');
});

test('untouched results hero keeps the existing evidence-building invitation',()=>{
 const dashboard=load({},[],{fallback:false});
 const hero=dashboard.heroModel({total:49,attempted:0,mastered:0,provisional:0,weak:0,unattempted:49});
 assert.equal(hero.mode,'empty');
 assert.equal(hero.primaryValue,'0 / 49');
 assert.equal(hero.primaryLabel,'已驗證掌握');
 assert.equal(hero.headline,'開始學習後，技能證據會在這裡累積');
});

test('dashboard weakest drilldown prioritizes recent mistakes then lower mastery at skill level',()=>{const dashboard=load({kp_virtual_er:{mastery:60,attempts:2,lastCorrect:false,lastAnsweredAt:'2026-09-10T12:00:00.000Z',misconceptions:{}},kp_virtual_yi:{mastery:20,attempts:2,lastCorrect:true,lastAnsweredAt:'2026-09-10T11:00:00.000Z',misconceptions:{'q::x':{count:4}}},kp_virtual_yu:{mastery:40,attempts:2,lastCorrect:false,lastAnsweredAt:'2026-09-10T10:00:00.000Z',misconceptions:{}}},[],{fallback:false});const particles=dashboard.build().groups.find(g=>g.id==='fw');assert.deepEqual(Array.from(dashboard.weakest(particles,3),x=>x.skillId),['fw.yu','fw.er','fw.yi'])});
test('dashboard trend insights use skill labels while aggregating KP practice evidence',()=>{const history=[{kpId:'kp_virtual_yi',delta:12,accuracy:80},{kpId:'kp_virtual_yi',delta:8,accuracy:100},{kpId:'kp_virtual_er',delta:2,accuracy:60},{kpId:'kp_virtual_er',delta:1,accuracy:40},{kpId:'kp_virtual_yu',delta:7,accuracy:80}];const trends=load(null,history).trendData();assert.equal(trends.improved[0].skillId,'fw.yi');assert.equal(trends.improved[0].label,'以');assert.equal(trends.improved[0].delta,20);assert.equal(trends.stuck[0].skillId,'fw.er');assert.equal(trends.stuck[0].sessions,2);assert.equal(trends.stuck[0].accuracy,50)});
test('dashboard does not flag strong skill practice as stuck just because gains are small',()=>{const knowledge={kp_virtual_zhi:{mastery:95,attempts:10,lastCorrect:true,lastAnsweredAt:'2026-09-10T12:00:00.000Z',misconceptions:{}},kp_p3_zhi:{mastery:95,attempts:10,lastCorrect:true,lastAnsweredAt:'2026-09-10T12:00:00.000Z',misconceptions:{}}},history=[{kpId:'kp_virtual_zhi',beforeMastery:92,afterMastery:94,delta:2,accuracy:100,strategy:'targeted'},{kpId:'kp_virtual_zhi',beforeMastery:94,afterMastery:95,delta:1,accuracy:100,strategy:'targeted'}],trends=load(knowledge,history, {fallback:false}).trendData();assert.equal(trends.stuck.some(x=>x.skillId==='fw.zhi'),false)});
test('results summarize failed and successful intervention states by skill',()=>{const knowledge={kp_virtual_er:{mastery:48,attempts:8,lastCorrect:false,lastAnsweredAt:'2026-09-10T12:00:00.000Z',misconceptions:{}},kp_virtual_yi:{mastery:62,attempts:8,lastCorrect:true,lastAnsweredAt:'2026-09-10T11:00:00.000Z',misconceptions:{}}},history=[{kpId:'kp_virtual_er',strategy:'remedial',beforeMastery:55,afterMastery:48,delta:-7,accuracy:50,conceptDelta:-10,completedAt:'2026-09-10T12:00:00Z'},{kpId:'kp_virtual_yi',strategy:'remedial',beforeMastery:54,afterMastery:62,delta:8,accuracy:100,conceptDelta:12,completedAt:'2026-09-10T11:00:00Z'}],summary=load(knowledge,history,{fallback:false}).effectivenessSummary();assert.equal(summary.items[0].skillId,'fw.er');assert.equal(summary.items[0].state.label,'需要概念重教');assert.equal(summary.attention.length,1);const stable=summary.items.find(x=>x.skillId==='fw.yi');assert.equal(stable.state.label,'補救後已穩定');assert.equal(summary.stable.length,1)});
test('intervention priority can outrank raw mastery in skill drilldown',()=>{const knowledge={kp_virtual_zhi:{mastery:10,attempts:5,lastCorrect:true,lastAnsweredAt:'2026-09-10T10:00:00.000Z',misconceptions:{}},kp_virtual_er:{mastery:55,attempts:8,lastCorrect:true,lastAnsweredAt:'2026-09-10T11:00:00.000Z',misconceptions:{}}},history=[{kpId:'kp_virtual_er',strategy:'remedial',beforeMastery:60,afterMastery:55,delta:-5,accuracy:50,conceptDelta:-8,completedAt:'2026-09-10T12:00:00Z'}],dashboard=load(knowledge,history,{fallback:false}),items=dashboard.weakest(dashboard.build().groups.find(g=>g.id==='fw'),3);assert.equal(items[0].skillId,'fw.er');assert.equal(items[0].practiceState.key,'reteach')});
test('ability trend counts practice evidence from skills in that domain',()=>{const dashboard=load(null,[{kpId:'kp_virtual_yi',delta:8,accuracy:100},{kpId:'kp_virtual_er',delta:4,accuracy:50},{kpId:'kp_translation_001',delta:20,accuracy:100}]),particles=dashboard.build().groups.find(g=>g.id==='fw'),trend=dashboard.groupTrendData(particles);assert.equal(trend.sessions,2);assert.equal(trend.totalDelta,12);assert.equal(trend.accuracy,75);assert.equal(trend.best.skillId,'fw.yi')});
test('results UI explicitly presents 49 core skills and six curriculum domains',()=>{const source=read('public/mastery-dashboard.js');assert.match(source,/49 項核心技能/);assert.match(source,/六大核心能力/);assert.match(source,/dashboard-hero/);assert.match(source,/已建立證據/);assert.match(source,/已建立 '.replace(' ',''));assert.match(source,/補強成效/);assert.match(source,/查看技能與近 7 天趨勢/);assert.match(source,/最需要補強的技能/);assert.match(source,/查看全部近 7 天技能趨勢/)});
test('dashboard drilldown keeps adaptive KP practice routes underneath skill cards',()=>{const source=read('public/mastery-dashboard.js');assert.match(source,/actionKpId/);assert.match(source,/lesson\.html\?kpId=/);assert.match(source,/mode=practice/);assert.match(source,/立即補強/);assert.match(source,/概念重教/);assert.match(source,/進入補救/)});
test('browser loader installs skill results before weakness and mastery surfaces',()=>{const rotation=read('public/question-rotation.js'),catalog=read('public/content-catalog.js');assert.match(rotation,/skill-mastery-v1\.js[\s\S]*skill-results-v1\.js[\s\S]*skill-first-plan\.js/);assert.match(catalog,/question-rotation\.js[\s\S]*weakness-panel\.js[\s\S]*mastery-dashboard\.js/)});
test('mastery dashboard consumes the shared skill results projection rather than raw KP totals',()=>{const source=read('public/mastery-dashboard.js');assert.match(source,/ManjingoSkillResultsV1/);assert.doesNotMatch(source,/knowledgePoints\.filter/);assert.match(source,/core skills|核心技能/i)});
