const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const curriculum=require('../public/curriculum-v1.js');
const metadata=require('../public/question-metadata-v1.js');
function source(file){return fs.readFileSync(path.join(root,file),'utf8')}
function loadCatalog(){const context={window:{},Map,Set,Array,Object,Number,String,Math};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/question-pack-transfer-07.js','public/content-catalog.js'])vm.runInContext(source(file),context,{filename:file});return context.window.ManjingoContent;}
function byId(questions,id){const found=questions.find(q=>q.id===id);assert.ok(found,`missing question ${id}`);return found;}
test('all 469 reviewed questions receive a curriculum mode',()=>{const questions=metadata.annotateAll(loadCatalog().questions),valid=new Set(curriculum.skills.map(x=>x.id));assert.equal(questions.length,469);assert.equal(questions.some(q=>q.curriculumMode==='unmapped'),false);for(const q of questions){assert.ok(['core','set-text','advanced'].includes(q.curriculumMode));assert.ok(Array.isArray(q.skillIds));if(q.curriculumMode==='core'||q.curriculumMode==='advanced')assert.ok(q.skillIds.length>0,`${q.id}: scheduled question has no skill`);for(const id of q.skillIds)assert.ok(valid.has(id),`${q.id}: unknown skill ${id}`);}});
test('metadata makes operational difficulty explicit without changing authored tiers',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.equal(q.every(row=>metadata.DIFFICULTY_TIERS.has(row.difficultyTier)),true);assert.equal(metadata.resolvedDifficultyTier({difficultyTier:'foundation'}),'foundation');assert.equal(metadata.resolvedDifficultyTier({difficultyTier:'transfer'}),'transfer');assert.equal(metadata.resolvedDifficultyTier({}),'application');assert.equal(metadata.resolvedDifficultyTier({difficultyTier:'unexpected'}),'application');});
test('source scope separates sentence, passage, concept, and cross-source evidence',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.equal(q.every(row=>metadata.SOURCE_SCOPES.has(row.sourceScope)),true);assert.equal(byId(q,'p3q025').sourceScope,'sentence');assert.equal(byId(q,'p2q064').sourceScope,'passage');assert.equal(byId(q,'p3q040').sourceScope,'concept');assert.equal(byId(q,'p3q004').sourceScope,'cross-source');const compared=metadata.annotate({id:'ad1q024',textId:'CROSS',q:'比較「見漁人，乃大驚」與「徒見欺」，兩個「見」依次是？'});assert.equal(compared.sourceScope,'cross-source');assert.equal(compared.sourceSentenceId,null);});
test('single-passage argument questions retain their real text provenance',()=>{const q=metadata.annotateAll(loadCatalog().questions);for(const[id,source]of [['p3q045','shengyouhuan'],['p3q046','yuwosuoyu'],['lpq061','yuwosuoyu']]){const row=byId(q,id);assert.equal(row.sourceTextId,source);assert.equal(row.sourceScope,'passage');assert.equal(row.sourceSentenceId,null);}});
test('pure set-text recall leaves normal core while transferable questions are salvaged',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.equal(byId(q,'q008').curriculumMode,'set-text');assert.equal(byId(q,'lpq052').curriculumMode,'set-text');assert.equal(byId(q,'p2q042').curriculumMode,'set-text');assert.deepEqual(Array.from(byId(q,'p2q041').skillIds),['lex.ancient-modern']);assert.deepEqual(Array.from(byId(q,'p2q057').skillIds),['lex.context-inference']);assert.deepEqual(Array.from(byId(q,'p2q071').skillIds),['syn.object-fronting']);assert.deepEqual(Array.from(byId(q,'p2q034').skillIds),['lex.causative']);assert.deepEqual(Array.from(byId(q,'cap1q025').skillIds),['fw.nai']);});
test('stage 1 and stage 2 transfer questions keep explicit skills provenance and transfer level',()=>{const q=metadata.annotateAll(loadCatalog().questions),checks=[['tr1q001','fw.zhi','lunyu'],['tr2q005','trans.reorder','lianpo'],['tr3q001','fw.wei','liuguolun'],['tr4q001','read.sentence-core','shishuo'],['tr5q001','syn.interrogative-patterns','lunyu'],['tr6q001','transfer.single-sentence','quanxue'],['tr7q001','fw.hu','shishuo'],['tr7q004','fw.qie','shishuo'],['tr7q010','fw.yan','lunyu'],['tr7q016','lex.tongjia','lunyu'],['tr7q022','lex.intentional','shishuo'],['tr7q028','lex.semantic-role','hongmenyan'],['tr8q001','lex.word-class-shift','hongmenyan'],['tr8q002','syn.adverbial-postpose','shishuo'],['tr8q003','syn.ellipsis-object','lianpo'],['tr8q004','syn.attributive-postpose','quanxue'],['tr8q010','syn.fixed-patterns','lunyu'],['tr8q016','read.parallel-inference','liuguolun'],['tr9q001','read.actor-tracking','hongmenyan'],['tr9q007','read.unknown-word-tolerance','youbaochanshanji'],['tr9q013','trans.fluency','lunyu'],['tr9q019','transfer.sentence-pair','quanxue'],['tr9q025','transfer.micro-passage','hongmenyan']];for(const[id,skill,sourceText]of checks){const row=byId(q,id);assert.ok(row.skillIds.includes(skill),`${id} must include ${skill}`);assert.equal(row.sourceTextId,sourceText);assert.equal(row.curriculumMode,'core');assert.equal(row.normalCore,true);assert.equal(row.sourceKind,'classical-canon');assert.ok(row.transferLevel>=2);}});
test('native stage 3 passage questions are advanced rather than normal-core questions',()=>{const q=metadata.annotateAll(loadCatalog().questions),checks=[['tr10q001','read.argumentation'],['tr10q007','transfer.short-passage'],['tr10q013','transfer.mixed'],['tr10q019','read.argumentation'],['tr10q025','transfer.short-passage'],['tr10q031','transfer.mixed']];for(const[id,skill]of checks){const row=byId(q,id);assert.deepEqual(Array.from(row.skillIds),[skill]);assert.equal(row.curriculumMode,'advanced');assert.equal(row.normalCore,false);assert.equal(row.transferLevel,3);assert.equal(row.sourceKind,'classical-canon');assert.ok(String(row.passageId||'').startsWith('passage:'));assert.ok(String(row.passageText||'').length>=35);}});
test('cross-tagged transfer evidence preserves every credited skill',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.deepEqual(Array.from(byId(q,'tr5q010').skillIds),['trans.function-word','syn.judgment']);assert.deepEqual(Array.from(byId(q,'tr5q017').skillIds),['trans.supplement','syn.ellipsis-subject']);assert.deepEqual(Array.from(byId(q,'tr5q019').skillIds),['trans.ancient-modern','lex.ancient-modern']);assert.deepEqual(Array.from(byId(q,'tr6q001').skillIds),['transfer.single-sentence','lex.context-inference']);assert.deepEqual(Array.from(byId(q,'tr6q003').skillIds),['transfer.single-sentence','lex.polysemy']);});
test('advanced argumentation remains available but does not compete in the normal language core',()=>{const q=metadata.annotateAll(loadCatalog().questions);for(const id of ['lpq055','lpq058','lpq061','p3q045','tr10q001','tr10q006','tr10q019','tr10q024']){const row=byId(q,id);assert.equal(row.curriculumMode,'advanced');assert.equal(row.normalCore,false);assert.deepEqual(Array.from(row.skillIds),['read.argumentation']);}});
test('sentence-level identity catches repeated wording across different question ids and packs',()=>{const q=metadata.annotateAll(loadCatalog().questions);for(const ids of [['q006','q010','cap1q013','cap1q014','cap1q015','p3q029','p3q041'],['p2q071','p2q072','lpq045','p3q030'],['tr2q001','tr3q004'],['tr1q002','tr4q013'],['tr1q001','tr5q007'],['tr3q001','tr5q009'],['tr7q004','tr7q015'],['p3q025','lpq036']])assert.equal(new Set(ids.map(id=>byId(q,id).sourceSentenceId)).size,1,`shared sentence mismatch: ${ids.join(',')}`);});
test('short quoted sentence ids are explicit while concept questions stay unassigned',()=>{const q=metadata.annotateAll(loadCatalog().questions);assert.equal(byId(q,'p3q025').sourceSentenceId,'sentence:lianpo-linxiangru:tu-jian-qi');const passive=metadata.annotate({id:'ad1q022',textId:'CROSS'}),fronting=metadata.annotate({id:'ad1q033',textId:'CROSS'});assert.equal(passive.sourceSentenceId,'sentence:lianpo-linxiangru:tu-jian-qi');assert.equal(passive.sourceTextId,'lianpo-linxiangru');assert.equal(fronting.sourceSentenceId,'sentence:caogui:heyi-zhan');assert.equal(fronting.sourceTextId,'caogui');for(const id of ['p2q028','p2q042','p2q081','p3q008','p3q045'])assert.equal(byId(q,id).sourceSentenceId,null,`${id}: concept or passage question must not claim a single source sentence`);});
test('legacy CROSS is separated from the real source text when provenance is known',()=>{const q=metadata.annotateAll(loadCatalog().questions),y=byId(q,'p3q009'),z=byId(q,'lpq007'),g=byId(q,'p3q008');assert.equal(y.legacyTextId,'CROSS');assert.equal(y.sourceTextId,'yueyanglou');assert.equal(y.sourceKind,'set-text');assert.equal(z.sourceTextId,'zuiwengtingji');assert.equal(z.sourceKind,'classical-canon');assert.equal(g.sourceTextId,'CROSS');assert.equal(g.sourceKind,'mixed');});
test('normal core filter excludes set-text recall and stage 3 without deleting the original catalog',()=>{const c=loadCatalog(),core=metadata.normalCoreQuestions(c.questions),ids=new Set(core.map(q=>q.id));assert.equal(c.questions.length,469);assert.equal(core.length,342);for(const id of ['q008','lpq053','p2q042','tr10q001','tr10q007','tr10q013','tr10q019','tr10q025','tr10q031'])assert.equal(ids.has(id),false);for(const id of ['p2q041','p2q071','p3q029','tr1q001','tr5q024','tr6q001','tr7q001','tr7q036','tr8q001','tr8q021','tr9q001','tr9q030'])assert.equal(ids.has(id),true);});
test('audit quantifies stage 3 as advanced and keeps normal core stable',()=>{const audit=metadata.audit(loadCatalog().questions);assert.equal(audit.total,469);assert.equal(Object.values(audit.byMode).reduce((a,b)=>a+b,0),469);assert.equal(audit.byMode.core,342);assert.equal(audit.byMode['set-text'],78);assert.equal(audit.byMode.advanced,49);assert.deepEqual(audit.bySourceScope,{sentence:408,passage:33,'cross-source':4,concept:24});assert.equal(audit.bySourceText.yueyanglou,38);assert.equal(audit.bySourceText.CROSS,42);assert.equal(audit.bySourceText.lunyu,33);assert.equal(audit.bySourceText.quanxue,28);assert.equal(audit.bySourceText['mengzi-lianghuiwang-xia'],6);assert.equal(audit.bySourceText.xiaoyaoyou,10);assert.equal(audit.bySourceText.lianpo,26);assert.equal(audit.bySourceText['xunzi-quanxue-stage3'],2);assert.equal(audit.bySourceText['zhanguoce-hujiahuwei'],2);assert.equal(audit.bySourceText['huainanzi-saiweng'],2);assert.equal(audit.bySourceText['hanfeizi-wudu-shouzhu'],3);assert.equal(audit.bySourceText['zhanguoce-yubang-xiangzheng'],3);assert.equal(audit.bySourceText['shishuo-xinyu-wangrong-li'],3);assert.equal(audit.bySourceText['liezi-liangxiaoer-biandou'],3);assert.equal(audit.bySourceText['zhanguoce-huashe-tianzu'],3);assert.equal(audit.bySourceText['lvshi-chunqiu-yaner-daozhong'],3);assert.ok(audit.bySourceText.chibifu>=11);assert.ok(audit.bySourceText.zhuzhiwutuiqinshi>=8);assert.ok(audit.bySourceText.lantingjixu>=2);assert.ok(audit.bySourceText.youbaochanshanji>=6);});
