const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const reorder=require('../public/reorder-question.js');
const verification=require('../public/answer-verification-v1.js');
const evidence=require('../public/skill-evidence-v1.js');

function pack(){const context={window:{}};vm.createContext(context);vm.runInContext(read('public/question-pack-reorder-01.js'),context);return context.window.ManjingoQuestionPackReorder01}
function question(id='rq007'){return pack().questions.find(item=>item.id===id)}
function reviewed(questionOverride={}){return{...question(),skillContractVersion:evidence.QUESTION_CONTRACT_VERSION,...questionOverride}}

test('reorder contract validates exact fragment use and exposes a readable model answer',()=>{const q=question();assert.equal(reorder.valid(q),true);assert.equal(reorder.isCorrect(q,'a|b|c|d'),true);assert.equal(reorder.isCorrect(q,'a|c|b|d'),false);assert.equal(reorder.modelAnswer(q),'宋國有甚麼罪呢？');assert.deepEqual(reorder.decode(reorder.encode(q.answerOrder)),Array.from(q.answerOrder));});
test('server authoritatively verifies reorder order and rejects missing or duplicate fragments',()=>{const q=question(),correct=verification.verify(q,'a|b|c|d'),wrong=verification.verify(q,'a|c|b|d');assert.equal(correct.isCorrect,true);assert.equal(correct.correctAnswer,'宋國有甚麼罪呢？');assert.equal(wrong.isCorrect,false);assert.throws(()=>verification.verify(q,'a|b'),error=>error.status===400&&/every question fragment exactly once/.test(error.message));assert.throws(()=>verification.verify(q,'a|b|b|d'),error=>error.status===400&&/every question fragment exactly once/.test(error.message));});
test('reviewed reorder pack spans sixteen questions, fifteen sources and three difficulty tiers',()=>{const questions=pack().questions;assert.equal(questions.length,16);assert.equal(new Set(questions.map(q=>q.sourceTextId)).size,15);assert.deepEqual(Array.from(new Set(questions.map(q=>q.difficultyTier))).sort(),['application','foundation','transfer']);assert.ok(questions.filter(q=>q.sourceKind==='classical-canon'&&q.transferLevel>=2&&q.difficultyTier==='transfer').length>=5);for(const q of questions){assert.equal(q.type,'reorder');assert.ok(Array.from(q.skillIds).includes('trans.reorder'));assert.equal(reorder.valid(q),true);assert.ok(q.explanation.length>=20);}});
test('choice-only evidence cannot produce a verified translation reorder skill',()=>{let state=evidence.empty();for(let i=0;i<5;i++){const q=reviewed({id:`choice${i%3}`,type:'choice',sourceTextId:`source${i%2}`});state=evidence.update(state,{isCorrect:true,localDate:i<3?'2026-09-10':'2026-09-12'},q,'trans.reorder',i<4?'2026-09-10T00:00:00.000Z':'2026-09-12T00:00:00.000Z');}const result=evidence.assess({skillId:'trans.reorder',mastery:100,lastCorrect:true,evidence:state});assert.equal(result.verified,false);assert.equal(result.checks.production,false);assert.deepEqual(result.evidence.productionQuestionIds,[]);});
test('three correct reorder questions across contexts plus delayed confirmation unlock production evidence',()=>{let state=evidence.empty();const attempts=[['rq001','2026-09-10','2026-09-10T00:00:00.000Z'],['rq003','2026-09-10','2026-09-10T01:00:00.000Z'],['rq007','2026-09-10','2026-09-10T02:00:00.000Z'],['rq001','2026-09-12','2026-09-12T00:00:00.000Z'],['rq007','2026-09-12','2026-09-12T01:00:00.000Z']];for(const[id,localDate,at]of attempts)state=evidence.update(state,{isCorrect:true,localDate},reviewed(question(id)),'trans.reorder',at);const result=evidence.assess({skillId:'trans.reorder',mastery:92,lastCorrect:true,evidence:state});assert.equal(result.verified,true);assert.equal(result.checks.production,true);assert.ok(result.evidence.productionQuestionIds.length>=3);assert.ok(result.evidence.productionContextIds.length>=2);assert.ok(result.evidence.productionDelayedCorrectAt);});
test('static runtime, importer and both practice surfaces include reorder metadata and UI',()=>{const catalog=read('public/content-catalog.js'),home=read('public/index.html'),lesson=read('public/local-lesson.js'),importer=read('scripts/import_to_firestore.js');assert.match(catalog,/question-pack-reorder-01\.js/);assert.match(catalog,/reorder-question\.js/);assert.match(home,/const api=reorderApi\(\);if\(!api\|\|typeof api\.mount!=='function'\)return null;api\.mount\(answers,q/);assert.match(lesson,/reorderApi\(\)\.mount\(host,q/);assert.match(importer,/fragments:Array\.isArray\(question\.fragments\)/);assert.match(importer,/answerOrder:Array\.isArray\(question\.answerOrder\)/);assert.match(importer,/modelAnswer:question\.modelAnswer/);});
