const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const read=p=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
function load(records,history=[]){const store=new Map(),context={window:{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},Map,Set,Object,Array,String,Number,Math,Date,JSON,RegExp,encodeURIComponent};vm.createContext(context);for(const file of ['public/question-pack-02.js','public/question-pack-03.js','public/question-pack-lesson.js','public/question-pack-capacity-01.js','public/question-pack-transfer-01.js','public/question-pack-transfer-03.js','public/question-pack-transfer-04.js','public/question-pack-transfer-05.js','public/question-pack-transfer-06.js','public/content-catalog.js','public/curriculum-v1.js','public/question-metadata-v1.js'])vm.runInContext(read(file),context);context.window.ManjingoLocalLearning={getKnowledge:id=>records[id]||{mastery:0,attempts:0,lastCorrect:null,lastAnsweredAt:null,misconceptions:{}},getPracticeHistory(opts={}){return history.filter(item=>!opts.kpId||String(item.kpId)===String(opts.kpId))}};vm.runInContext(read('public/practice-effectiveness.js'),context);context.window.ManjingoPracticeEffectiveness=context.ManjingoPracticeEffectiveness;vm.runInContext(read('public/skill-mastery-v1.js'),context);vm.runInContext(read('public/skill-results-v1.js'),context);context.document={readyState:'loading',addEventListener(){}};vm.runInContext(read('public/weakness-panel.js'),context);return context.window.ManjingoWeaknessPanel;}
test('weakness diagnosis prioritizes at most three core skills and excludes untouched skills',()=>{const panel=load({kp_virtual_er:{mastery:40,attempts:2,lastCorrect:true,lastAnsweredAt:'2026-09-10T12:00:00Z',misconceptions:{}},kp_virtual_yu:{mastery:55,attempts:2,lastCorrect:false,lastAnsweredAt:'2026-09-10T11:00:00Z',misconceptions:{}},kp_virtual_qi:{mastery:58,attempts:1,lastCorrect:true,lastAnsweredAt:'2026-09-10T10:00:00Z',misconceptions:{}},kp_virtual_zhi:{mastery:75,attempts:3,lastCorrect:true,lastAnsweredAt:'2026-09-10T09:00:00Z',misconceptions:{q004:{questionId:'q004',count:3,selectedAnswer:'結構助詞（的）',correctAnswer:'動詞（到／往）'}}}});const result=panel.diagnosis();assert.equal(result.priority.length,3);assert.equal(result.priority.every(x=>x.skillId),true);assert.equal(result.otherWeak.length,1);assert.equal(result.otherWeak[0].skillId,'fw.qi');assert.equal(result.patterns.length,1);assert.equal(result.patterns[0].skillId,'fw.zhi');assert.match(panel.describe(result.patterns[0]),/常把「動詞（到／往）」誤答成「結構助詞（的）」/)});
test('failed KP intervention outranks raw skill mastery and keeps a concrete practice route',()=>{const panel=load({kp_virtual_er:{mastery:15,attempts:4,lastCorrect:true,lastAnsweredAt:'2026-09-10T10:00:00Z',misconceptions:{}},kp_virtual_zhi:{mastery:68,attempts:6,lastCorrect:true,lastAnsweredAt:'2026-09-10T12:00:00Z',misconceptions:{}}},[{kpId:'kp_virtual_zhi',strategy:'remedial',beforeMastery:70,afterMastery:68,delta:-2,accuracy:50,conceptDelta:-8,completedAt:'2026-09-10T12:00:00Z'}]);const result=panel.diagnosis();assert.equal(result.priority[0].skillId,'fw.zhi');assert.equal(result.priority[0].practiceState.label,'需要概念重教');assert.ok(result.priority[0].kpId);assert.equal(panel.stateAction(result.priority[0].practiceState),'開始概念重教')});
test('recently effective practice cools a still-low-mastery skill out of weakness priority',()=>{const panel=load({kp_virtual_er:{mastery:40,attempts:4,lastCorrect:true,lastAnsweredAt:'2026-09-10T12:00:00Z',misconceptions:{}}},[{practiceId:'pr_er_effective',skillId:'fw.er',kpId:'kp_virtual_er',routeKpId:'kp_virtual_er',strategy:'targeted',beforeMastery:30,afterMastery:40,delta:10,accuracy:80,correctCount:4,questionCount:5,completedAt:'2026-09-10T12:05:00Z'}]);const weak=panel.weakKnowledgePoints(),result=panel.diagnosis();assert.equal(panel.isCoolingState({key:'targeted-effective'}),true);assert.equal(weak.some(x=>x.skillId==='fw.er'),false);assert.equal(result.priority.some(x=>x.skillId==='fw.er'),false);assert.equal(result.otherWeak.some(x=>x.skillId==='fw.er'),false)});
test('weak skill list collapses multiple KP aliases into one learner-facing weakness',()=>{const panel=load({kp_virtual_yi:{mastery:30,attempts:2,lastCorrect:false,lastAnsweredAt:'2026-09-10T12:00:00Z',misconceptions:{}},kp_p3_yi:{mastery:45,attempts:3,lastCorrect:true,lastAnsweredAt:'2026-09-09T12:00:00Z',misconceptions:{}}}),weak=panel.weakKnowledgePoints().filter(x=>x.skillId==='fw.yi');assert.equal(weak.length,1);assert.equal(weak[0].label,'以');assert.ok(weak[0].kpId)});
test('weakness panel presents skill-level priority patterns and secondary weaknesses while keeping targeted practice',()=>{const source=read('public/weakness-panel.js');assert.match(source,/技能弱點診斷/);assert.match(source,/最需要處理的技能/);assert.match(source,/常見錯誤模式/);assert.match(source,/其他技能弱項/);assert.match(source,/slice\(0,3\)/);assert.match(source,/ManjingoSkillResultsV1/);assert.match(source,/lesson\.html\?kpId=/);assert.match(source,/&mode=practice/);assert.match(source,/立即補強/)});
test('browser runtime loads skill results before weakness diagnosis',()=>{const rotation=read('public/question-rotation.js'),catalog=read('public/content-catalog.js');assert.match(rotation,/skill-results-v1\.js/);assert.match(catalog,/question-rotation\.js[\s\S]*weakness-panel\.js/)});
test('weakness panel no longer enumerates raw knowledge points as the primary diagnosis surface',()=>{const source=read('public/weakness-panel.js');assert.doesNotMatch(source,/catalog\.knowledgePoints\.filter/);assert.match(source,/allItems\(\)/);assert.match(source,/skillId/)});
