const fs=require('node:fs');
const path=require('node:path');
const {loadReviewedCatalog}=require('./reviewed_catalog.js');

const root=path.join(__dirname,'..');
const outputPath=path.join(root,'public','server-kp-universe.js');

function buildRows(catalog){
  const skillIdsByKp=new Map();
  for(const question of catalog.questions||[]){
    const kpId=String(question.kpId||'');
    if(!kpId)continue;
    const skills=skillIdsByKp.get(kpId)||new Set();
    for(const skillId of question.skillIds||[])skills.add(String(skillId));
    skillIdsByKp.set(kpId,skills);
  }
  return (catalog.knowledgePoints||[]).map(kp=>({
    id:String(kp.kpId),
    data:{
      textId:kp.textId==='CROSS'?null:(kp.textId||null),
      type:kp.type||null,
      teachable:kp.teachable!==false,
      skillIds:Array.from(skillIdsByKp.get(String(kp.kpId))||[]).sort(),
      catalogVersion:String(catalog.catalogVersion||'reviewed')
    }
  })).sort((a,b)=>a.id.localeCompare(b.id));
}

function render(catalog){
  const rows=buildRows(catalog);
  const version=`server-kp-universe-${String(catalog.catalogVersion||'reviewed')}`;
  return `// Generated by scripts/build_server_kp_universe.cjs. Do not edit by hand.\n(function(root,factory){\n'use strict';\nconst api=factory();\nif(typeof module==='object'&&module.exports)module.exports=api;\nroot.ManjingoServerKpUniverse=api;\nif(root.window&&root.window!==root)root.window.ManjingoServerKpUniverse=api;\n})(typeof globalThis!=='undefined'?globalThis:this,function(){\n'use strict';\nconst VERSION=${JSON.stringify(version)};\nconst CATALOG_VERSION=${JSON.stringify(String(catalog.catalogVersion||'reviewed'))};\nconst rows=${JSON.stringify(rows)};\nreturn{VERSION,CATALOG_VERSION,rows};\n});\n`;
}

if(require.main===module){
  const expected=render(loadReviewedCatalog(root));
  if(process.argv.includes('--check')){
    const current=fs.existsSync(outputPath)?fs.readFileSync(outputPath,'utf8'):'';
    if(current!==expected){
      console.error('public/server-kp-universe.js is stale; run node scripts/build_server_kp_universe.cjs');
      process.exit(1);
    }
    console.log('Server KP universe bundle is current.');
  }else{
    fs.writeFileSync(outputPath,expected);
    console.log(`Wrote ${path.relative(root,outputPath)}`);
  }
}

module.exports={buildRows,render};
