'use strict';

const fs=require('node:fs');
const path=require('node:path');
const {loadReviewedCatalog}=require('./reviewed_catalog.js');

const root=path.join(__dirname,'..');
const output=path.join(root,'public','server-question-index.js');

function questionData(question,catalogVersion){
 return{
  type:question.type,kpId:question.kpId,textId:question.textId==='CROSS'?null:(question.textId||null),
  options:Array.isArray(question.o)?Array.from(question.o,String):[],answer:question.a==null?'':String(question.a),acceptedAnswers:Array.isArray(question.acceptedAnswers)?question.acceptedAnswers.map(String):[],
  fragments:Array.isArray(question.fragments)?question.fragments.map(item=>({id:String(item.id),text:String(item.text)})):[],answerOrder:Array.isArray(question.answerOrder)?question.answerOrder.map(String):[],modelAnswer:question.modelAnswer||null,reorderMode:question.reorderMode||null,requiredCount:Number.isInteger(question.requiredCount)?question.requiredCount:null,
  misconceptionKey:question.misconceptionKey||null,misconceptionLabel:question.misconceptionLabel||null,
  skillIds:Array.isArray(question.skillIds)?Array.from(question.skillIds,String):[],skillContractVersion:question.skillContractVersion||null,sourceTextId:question.sourceTextId||null,sourceSentenceId:question.sourceSentenceId||null,sourceScope:question.sourceScope||null,
  baseXp:Number(question.baseXp||question.xp||8),catalogVersion
 };
}

function build(){
 const catalog=loadReviewedCatalog(root),version=String(catalog.catalogVersion||'reviewed');
 const rows=catalog.questions.map(question=>[String(question.id),questionData(question,version)]);
 return `/* Generated by scripts/build_server_question_index.cjs from the reviewed catalog. Do not edit directly. */\n(function(root){'use strict';const rows=${JSON.stringify(rows)};const byId=new Map(rows);root.ManjingoServerQuestionIndex={version:${JSON.stringify(version)},count:rows.length,get(id){const data=byId.get(String(id));return data?{id:String(id),data}:null}};})(typeof globalThis!=='undefined'?globalThis:this);\n`;
}

const expected=build();
if(process.argv.includes('--check')){
 const current=fs.existsSync(output)?fs.readFileSync(output,'utf8'):'';
 if(current!==expected){console.error('public/server-question-index.js is stale; run node scripts/build_server_question_index.cjs');process.exit(1)}
 console.log('Server question index is current.');
}else{
 fs.writeFileSync(output,expected);
 console.log(`Wrote ${path.relative(root,output)}`);
}

module.exports={build,questionData};
